server:
  port: 8080

spring:
  application:
    name: booklay-gateway

logging:
  level:
    root: debug

  cloud:
    gateway:
      routes:
        - id: shop-service
          uri: http://192.168.0.111:80
          predicates:
            - Path=/shop/v1/**
            - Method=GET, POST, PUT, DELETE, PATCH
          filters:
            - RewritePath=/shop/v1/(?<segment>.*), /$\{segment}

        - id: coupon-service
          uri: http://133.186.228.19:8090
          predicates:
            - Path=/coupon/v1/**
            - Method=GET, POST, PUT, DELETE, PATCH
          filters:
            - RewritePath=/coupon/v1/(?<segment>.*), /$\{segment}

booklay:
  jwt:
    secret: cQfTjWmZq4t7w!z%C*F-JaNdRgUkXp2r5u8x/A?D(G+KbPeShVmYq3t6v9y$B&E)