server:
  port: 8080

spring:
  application:
    name: booklay-gateway

  cloud:
    gateway:
      routes:
        - id: shop-service
          uri: http://192.168.0.111:80
          predicates:
            - Path=/shop/v1/**
            - Method=GET, POST, PUT, DELETE, PATCH
          filters:
            - RewritePath=/shop/v1/(?<segment>.*), /$\{segment}

        - id: coupon-service
          uri: http://133.186.228.19:8090
          predicates:
            - Path=/coupon/v1/**
            - Method=GET, POST, PUT, DELETE, PATCH
          filters:
            - RewritePath=/coupon/v1/(?<segment>.*), /$\{segment}

        - id: auth-service
          uri: http://133.186.159.206:5050
          predicates:
            - Path=/auth/v1/**
            - Method=GET, POST, PUT, DELETE, PATCH
          filters:
            - RewritePath=/auth/v1/(?<segment>.*), /$\{segment}

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://133.186.250.128:6060"
              - "http://booklay.shop"
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

booklay:
  jwt:
    secret: cQfTjWmZq4t7w!z%C*F-JaNdRgUkXp2r5u8x/A?D(G+KbPeShVmYq3t6v9y$B&E)
